// Flat type aliases over the openapi-typescript output in `./types.ts`.
// `types.ts` is regenerated by `just gen-types` and its shape (paths/components)
// is not meant to be imported directly elsewhere — import from here instead.
import type { components } from "./types";

export type FieldValue = components["schemas"]["FieldValue"];
export type FieldSchema = components["schemas"]["FieldSchema"];
export type LogEntry = components["schemas"]["LogEntry"];
export type ActivitySummary = components["schemas"]["ActivitySummary"];
export type ActivityDetail = components["schemas"]["ActivityDetail"];
export type CreateActivity = components["schemas"]["CreateActivity"];
export type CreateEntry = components["schemas"]["CreateEntry"];
export type UpdateEntry = components["schemas"]["UpdateEntry"];
export type ActivityStats = components["schemas"]["ActivityStats"];
export type DailyCount = components["schemas"]["DailyCount"];
export type FieldStat = components["schemas"]["FieldStat"];
export type FieldStatPoint = components["schemas"]["FieldStatPoint"];
export type Period = components["schemas"]["Period"];
