// Generated by `just gen-types` — do not edit manually.
// Run `just gen-types` (with backend running) to refresh from /openapi.json.

export interface FieldValue {
  label: string;
  value: number;
}

export interface FieldSchema {
  label: string;
  last_value: number;
}

export interface LogEntry {
  id: number;
  activity_id: number;
  logged_at: number;
  values: FieldValue[];
  comment?: string | null;
}

export interface ActivitySummary {
  id: number;
  name: string;
  created_at: number;
  last_logged_at: number | null;
  entry_count: number;
}

export interface ActivityDetail {
  id: number;
  name: string;
  created_at: number;
  last_entries: LogEntry[];
  field_schema: FieldSchema[];
}

export interface CreateActivity {
  name: string;
}

export interface CreateEntry {
  values: FieldValue[];
  /** Unix timestamp seconds; omit to default to now */
  logged_at?: number;
  comment?: string;
}

export interface UpdateEntry {
  values: FieldValue[];
  logged_at: number;
  /** If provided, renames the parent activity for all its entries */
  activity_name?: string;
  comment?: string;
}

export interface DailyCount {
  date: string;
  count: number;
}

export interface FieldStatPoint {
  date: string;
  sum: number;
  avg: number;
}

export interface FieldStat {
  label: string;
  data: FieldStatPoint[];
}

export interface ActivityStats {
  period: string;
  counts: DailyCount[];
  field_stats: FieldStat[];
}
