/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_activities"];
        put?: never;
        post: operations["create_activity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activity_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_entry"];
        post?: never;
        delete: operations["delete_entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_activity"];
        put?: never;
        post?: never;
        delete: operations["delete_activity"];
        options?: never;
        head?: never;
        patch: operations["rename_activity"];
        trace?: never;
    };
    "/activities/{id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityDetail: {
            /** Format: int64 */
            created_at: number;
            /** @description Inferred from last entry; empty if no entries exist yet */
            field_schema: components["schemas"]["FieldSchema"][];
            /** Format: int64 */
            id: number;
            /** @description Last 10 entries, most recent first */
            last_entries: components["schemas"]["LogEntry"][];
            name: string;
        };
        ActivityStats: {
            counts: components["schemas"]["DailyCount"][];
            field_stats: components["schemas"]["FieldStat"][];
            period: string;
        };
        ActivitySummary: {
            /** Format: int64 */
            created_at: number;
            /** Format: int64 */
            entry_count: number;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            last_logged_at?: number | null;
            name: string;
        };
        CreateActivity: {
            name: string;
        };
        CreateEntry: {
            comment?: string | null;
            /**
             * Format: int64
             * @description Unix timestamp seconds; omit to default to now
             */
            logged_at?: number | null;
            values: components["schemas"]["FieldValue"][];
        };
        DailyCount: {
            /** Format: int64 */
            count: number;
            date: string;
        };
        FieldSchema: {
            label: string;
            /** Format: double */
            last_value: number;
        };
        FieldStat: {
            data: components["schemas"]["FieldStatPoint"][];
            label: string;
        };
        FieldStatPoint: {
            /** Format: double */
            avg?: number | null;
            date: string;
            /** Format: double */
            sum?: number | null;
        };
        FieldValue: {
            label: string;
            /** Format: double */
            value: number;
        };
        LogEntry: {
            /** Format: int64 */
            activity_id: number;
            comment?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            logged_at: number;
            values: components["schemas"]["FieldValue"][];
        };
        /** @enum {string} */
        Period: "day" | "week" | "month";
        UpdateEntry: {
            /** @description If provided, renames the parent activity (affects all its entries) */
            activity_name?: string | null;
            comment?: string | null;
            /** Format: int64 */
            logged_at: number;
            values: components["schemas"]["FieldValue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_activities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySummary"][];
                };
            };
        };
    };
    create_activity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivity"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySummary"];
                };
            };
        };
    };
    update_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                activity_id: number;
                /** @description Entry ID */
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                activity_id: number;
                /** @description Entry ID */
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename_activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivity"];
            };
        };
        responses: {
            /** @description Renamed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntry"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query: {
                /** @description day | week | month */
                period: string;
            };
            header?: never;
            path: {
                /** @description Activity ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityStats"];
                };
            };
        };
    };
}
